apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-test-1-bigip-ctlr
  labels:
    app: f5-test-1-bigip-ctlr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5-test-1-bigip-ctlr
  template:
    metadata:
      name: f5-test-1-bigip-ctlr
      labels:
        app: f5-test-1-bigip-ctlr
    spec:
      serviceAccountName: f5-test-2
      containers:
        - name: f5-test-1-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:2.5.0"
          #image: "f5networks/k8s-bigip-ctlr:2.4.0"
          #image: "f5networks/k8s-bigip-ctlr:2.3.0"
          #image: "vli39/k8s-bigip-ctlr:C3456795"
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
              - curl
              - -k
              - -s
              - -o
              - /dev/null
              - https://192.168.200.204
            initialDelaySeconds: 15
            periodSeconds: 15
            successThreshold: 1
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: f5-2-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f5-2-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--namespace-label=cis_scanner=test",
            "--log-level=INFO",
            "--bigip-url=192.168.200.204",
            "--insecure=true",
            "--bigip-partition=k8s",
            "--pool-member-type=cluster",
            "--custom-resource-mode=true",
            "--agent=as3"
            ]
