apiVersion: v1
kind: Namespace
metadata:
  name: f5-bigip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5-bigip-controller
  namespace: f5-bigip
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: f5-bigip-controller
rules:
- apiGroups: ["", "extensions", "networking.k8s.io"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions", "networking.k8s.io"]
  resources: ["configmaps", "events", "ingresses/status", "services/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["cis.f5.com"]
  resources: ["virtualservers","virtualservers/status", "tlsprofiles", "transportservers", "ingresslinks", "externaldnss"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["fic.f5.com"]
  resources: ["f5ipams", "f5ipams/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: f5-bigip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: f5-bigip-controller
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: f5-bigip-controller
  namespace: f5-bigip
