#                "protected": "{"alg":"dir","enc":"default"}"
kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-test01
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "configmap01",
        "label": "f5_test",
        "remark": "HTTP application",
        "f5_test": {
          "class": "Tenant",
          "f5_test_1": {
            "class": "Application",
            "template": "generic",
            "pool_monitor": {
              "class": "Monitor",
              "monitorType": "http",
              "send": "GET /version/ /HTTP/1.1\r\nHost: f5.1.com\r\n\r\n",
              "interval": 5,
              "timeout": 16,
              "receive": "version"
            },
            "cookie_encryption": {
              "class": "Persist",
              "persistenceMethod": "cookie",
              "cookieMethod": "insert",
              "encrypt": true,
              "passphrase": {
                "ciphertext": "a3RjeGZ5Z2Q=",
                "protected": "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0="
             }
            },
            "app_1_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "iRules": ["iRules_int"],
              "virtualAddresses": [
                "197.18.160.14"
              ],
              "persistenceMethods": [{
                "use": "cookie_encryption"
              }],
              "virtualPort": 8001,
              "serviceDownImmediateAction": "drop",
              "snat": "auto",
              "pool": "app_1_svc_pool"
            },
            "iRules_int": {
              "class": "iRule",
              "iRule": "when HTTP_REQUEST { HTTP::header insert X-Forwarded-For [IP::remote_addr] }"
            },
            "app_1_svc_pool": {
              "class": "Pool",
              "monitors": [{
                "use": "pool_monitor"
              }],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": [ ]
              }
              ]
            }
          }
        }
      }
    }


