apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-1
  name: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - image: artifactory.dev.cmbc.cn:31344/fhcloud-docker-sit-local/backend:0.0.6
        name: backend-1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-1
    cis.f5.com/as3-tenant: f5_test
    cis.f5.com/as3-app: f5_test_1
    cis.f5.com/as3-pool: app_1_svc_pool
  name: app-svc-1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: app-1
  sessionAffinity: None
  type: ClusterIP
