apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-2
  name: app-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
      - image: artifactory.dev.cmbc.cn:31344/fhcloud-docker-sit-local/echoserver:1.1
        name: backend-2
        ports:
        - containerPort: 8877
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-2
    cis.f5.com/as3-tenant: f5_test_2
    cis.f5.com/as3-app: f5_test_2
    cis.f5.com/as3-pool: app_2_svc_pool
  name: app-svc-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8877
  selector:
    app: app-2
  sessionAffinity: None
  type: ClusterIP
