kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-test02
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "one_partition_two_vs",
        "label": "f5_test",
        "remark": "HTTP application",
        "f5_test_2": {
          "class": "Tenant",
          "f5_test_2": {
            "class": "Application",
            "template": "generic",
            "app_2_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "197.18.160.14"
              ],
              "virtualPort": 8010,
              "snat": "auto",
              "pool": "app_2_svc_pool"
            },
            "app_2_svc_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": [ ]
              }
              ]
            }
          }
        }
      }
    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-test03
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "test03",
        "label": "f5_test",
        "remark": "HTTP application",
        "f5_test_3": {
          "class": "Tenant",
          "f5_test_3": {
            "class": "Application",
            "template": "generic",
            "app_3_svc_vs": {
              "class": "Service_HTTP",
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "197.18.160.76"
              ],
              "virtualPort": 8020,
              "snat": "auto",
              "pool": "app_3_svc_pool"
            },
            "app_3_svc_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": [ ]
              }
              ]
            }
          }
        }
      }
    }

