apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual01
  labels:
    f5cr: "true"
spec:
  #host: f5.1.com
  virtualServerAddress: "197.18.160.14"
  virtualServerHTTPPort: 8009
  pools:
  - path: /
    service: app-svc-2
    servicePort: 8080
    monitor:
      type: http
      send: “HTTP /rn”
      recv: ""
      interval: 5
      timeout: 16
---
apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual03
  labels:
    f5cr: "true"
spec:
  #host: f5.2.com
  virtualServerAddress: "197.18.160.76"
  virtualServerHTTPPort: 8010
  pools:
  - path: /
    service: app-svc-3
    servicePort: 8080
    monitor:
      type: http
      send: “HTTP /rn”
      recv: ""
      interval: 5
      timeout: 16
