kind: ConfigMap
apiVersion: v1
metadata:
  name: configmap-test03_ratio
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "action": "deploy",
      "persist": true, 
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.25.0",
        "id": "ratio_irule",
        "label": "f5_test_ratio",
        "remark": "HTTP application",
        "f5_test_3": {
          "class": "Tenant",
          "f5_test_3": {
            "class": "Application",
            "template": "generic",
            "app_3_svc_vs": {
              "class": "Service_HTTP",
              "iRules": ["iRules_int"],
              "persistenceMethods": [ "cookie" ],
              "virtualAddresses": [
                "197.18.160.14"
              ],
              "virtualPort": 8003,
              "snat": "auto",
              "pool": "app_3_svc_pool"
            },
            "iRules_int": {
              "class": "iRule",
              "remark": "switch between pools",
              "iRule": "when HTTP_REQUEST { \n if { [format %0.2f [expr {rand()}]] < 0.5 } { \n pool app_3_svc_pool \n } else { \n pool app_3_irule_svc_pool \n } \n }"
            },
            "app_3_svc_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": [ ]
              }
              ]
            },
            "app_3_irule_svc_pool": {
              "class": "Pool",
              "monitors": [
                "http"
              ],
              "loadBalancingMode": "least-connections-member",
              "members": [
              {
                "servicePort": 8080,
                "serverAddresses": [ ]
              }
              ]
            }
          }
        }
      }
    }

