apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: virtual01
  labels:
    f5cr: "true"
spec:
  #host: f5.1.com
  virtualServerAddress: "197.18.160.14"
  virtualServerHTTPPort: 8007
  pools:
  - path: /
    service: app-svc-2
    servicePort: 8080
    monitor:
      type: http
      send: “GET /rn”
      interval: 5
      timeout: 16

