kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: f5-bigip-controller
rules:
- apiGroups: ["", "extensions"]
  resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "events", "ingresses/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["", "extensions"]
  resources: ["secrets"]
#  resourceNames: ["bigip-login"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: f5-bigip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: f5-bigip-controller
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: f5-bigip-controller
  namespace: f5-bigip
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: f5-bigip-controller
  namespace: f5-bigip
